<?php
if($block->isEnable() == 1){ 
    if(!$block->isLoggedIn()): ?>
        <div id="signin-popup" style="display:none">
            <div id="popup-modal" >
                <form class="form form-login popup-signin"
                      method="post"
                      id="login-form"
                      data-mage-init='{"validation":{}}'>
                    <?= $block->getBlockHtml('formkey') ?>
                    <fieldset class="fieldset login" data-hasrequired="<?= $block->escapeHtmlAttr(__('* Required Fields')) ?>">
                        <div class="error-message-signin"></div>
                        <div class="field email-popup required">
                            <label class="label" for="email"><span><?= $block->escapeHtml(__('Email')) ?></span></label>
                            <div class="control">
                                <input name="login[username]" value="<?= $block->escapeHtmlAttr($block->getUsername()) ?>" <?php if ($block->isAutocompleteDisabled()) : ?> autocomplete="off"<?php endif; ?> id="email" type="email" class="input-text" title="<?= $block->escapeHtmlAttr(__('Email')) ?>" data-mage-init='{"mage/trim-input":{}}' data-validate="{'required':true, 'validate-email':true}">
                            </div>
                        </div>
                        <div class="field password-popup required">
                            <label for="pass" class="label"><span><?= $block->escapeHtml(__('Password')) ?></span></label>
                            <div class="control">
                                <input name="login[password]" type="password" <?php if ($block->isAutocompleteDisabled()) : ?> autocomplete="off"<?php endif; ?> class="input-text" id="pass" title="<?= $block->escapeHtmlAttr(__('Password')) ?>" data-validate="{'required':true}">
                            </div>
                        </div>
                        <?= $block->getChildHtml('form_additional_info') ?>
                        <div class="forgotpassword">
                            <div class="secondary"><a class="action remind" href="<?= $block->escapeUrl($block->getForgotPasswordUrl()) ?>"><span><?= $block->escapeHtml(__('Forgot Your Password?')) ?></span></a></div>
                        </div>
                        <div class="actions-toolbar">
                            <div class="primary"><button type="submit" class="action login primary signinup-btn" name="send" id="send2"><span><?= $block->escapeHtml(__('Log In')) ?></span></button></div>
                        </div>
                        <div class="register-linkpopup"><span><?php echo __('New Here?') ?></span>&nbsp;<a href="#" class="register-sigininpopup"><?php echo __('Register') ?></a></div>
                    </fieldset>
                </form>
            </div>
        </div>

<script type="text/javascript">
    require([
        'jquery',
        'Magento_Ui/js/modal/modal'
        ], function($,modal) {
        var options = {
                'type': 'popup',
                'title': 'Sign In',
                'responsive': true,
                'innerScroll': true,
                 buttons: []
            };

            $(document).ready(function(){
                $('.signup').on('click', function(loginevent){
                    loginevent.preventDefault();
                    var popup = modal(options, $('#signin-popup')); 
                    $("#signin-popup").modal("openModal");
                });
                $('.signinup-btn').click(function(e){
                    var siginindata = $('.popup-signin').serialize();
                    var urlsiginin = "<?php echo $block->getBaseUrl().'ajaxlogin/account/loginpopup/' ?>";
                    if ($('.popup-signin').valid()) {
                        $.ajax({
                            url: urlsiginin,
                            type: "POST",
                            data: siginindata,
                            success: function(data){
                                
                                if(data.error) {
                                    $('.error-message-signin').empty().append('<div class="message message-error error">'+data.message+'</div>');
                                }
                                else{                                        
                                    $('.error-message-signin').empty().append('<div class="message-success success message">'+data.message+'</div>');
                                    location.reload();
                                }                                
                            }
                        });
                    }
                    else{
                        e.preventDefault();
                    }
                    return false;
                });
                var optionregister = {
                    'type': 'popup',
                    'title': 'Create An New Account',
                    'responsive': true,
                    'innerScroll': true,
                    'buttons': []
                };
                $('.register-sigininpopup').on('click', function(registerevent){
                    registerevent.preventDefault();
                    var popup = modal(optionregister, $('.create-an-accountnew')); 
                    $("#signin-popup").modal("closeModal");
                    $(".create-an-accountnew").modal("openModal");
                });

            });
    });
</script>
<?php endif; 
}?>